apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: runtime-config
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane
      annotations:
        iam.gke.io/gcp-service-account: hackday-gke-admin@rhenus-hackathon.iam.gserviceaccount.com

---

apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectID: rhenus-hackathon
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds