---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  template:
    spec:
      containers:
      - name: order-service
        image: eu.gcr.io/rhenus-hackathon/argo-dc/order-service:main