apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: storage-runtime-config
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane
      annotations:
        iam.gke.io/gcp-service-account: hackday-gke-admin@rhenus-hackathon.iam.gserviceaccount.com
